# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3068d4daa7cf97a1e75d8829248ab5739d17776b80e00dd12c73c75ea179f0948d44655369ce2d6f786c36cfa8de626877e2fc89c804be275ea290f1389465e7

test:
  secret_key_base: eb5f03b3eadeef0fa3f62bcdad8605a677ee0bf2f71a2da3dc5f69096b6f6d855918d06fecdec255a8e19ee8fd43058fd52260940b5144e90650269dd8cb1924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
